ci: Upload static build artifacts
Make static builds and upload them as artifacts.
This makes it possible to download the binary produced for each PR.
In a follow up PR we could also automate binary upload upon release
as well as enabling cross compilation for different arch and OS.

Note that we use musl-gcc as it allows to statically link a libc
implementation while CGO_ENABLED=0 only was leading to the error below:
```
ethermint@v0.22.0-sdk50-1/app/ante/eip712.go:293:36: undefined: secp256k1.RecoverPubkey
ethermint@v0.22.0-sdk50-1/app/ante/eip712.go:319:17: undefined: secp256k1.VerifySignature
```
The statically linked binary is 100M as of today.

Also drop get-diff-action as it's unmaintained and was misbehaving on
the rebasing and squashing workflow, refs #139